Update conditional-jobs.yml

diff --git a/.github/workflows/conditional-jobs.yml b/.github/workflows/conditional-jobs.yml
--- a/.github/workflows/conditional-jobs.yml
+++ b/.github/workflows/conditional-jobs.yml
@@ -18,22 +18,36 @@ jobs:
           echo "How did we get here...."
           exit 1
 
-  always-skips-due-to-needs:
+  skips-due-to-needs:
     runs-on: ubuntu-latest
     needs: [never-runs]
     steps:
       - run: |
           echo "How did we get here...."
           exit 1
-  
-  always-skips-due-to-needs--longform:
+
+  skips-due-to-needs--success-func-has-bad-docs:
     runs-on: ubuntu-latest
     needs: [never-runs]
-    # success() already checks for past failures + cancellations
-    # there isn't a way for us to say "all items in array are a value"
+    # https://docs.github.com/en/actions/learn-github-actions/expressions#success
+    # "Returns true when none of the previous steps have failed or been canceled."
+    #
+    # Not true, it also returns false when the needed steps have been skipped
+    # Note: this is the default if you don't define 'if'
+    if: success()
+    steps:
+      - run: |
+          echo "How did we get here...."
+          exit 1
+
+  skips-due-to-needs--longform:
+    runs-on: ubuntu-latest
+    needs: [never-runs]
+    # This is as close as we can get to the behaviour of success()
+    # Note: there isn't a way for us to say "all items in array are a value"
     if: |
-      success()
-      && ! (
+      !(cancelled() || failure())
+      && !(
         contains(needs.*.result, 'skipped')
       )
     steps:
@@ -49,7 +63,7 @@ jobs:
     steps:
       - run: |
           echo "Hello, there 👀"
-  
+
   always-runs-ignoring-needs--permit-failures:
     needs: [never-runs]
     runs-on: ubuntu-latest
@@ -58,20 +72,21 @@ jobs:
     steps:
       - run: |
           echo "Hello, again"
-  
-  always-runs-ignoring-needs:
+
+  runs-ignoring-needs:
     needs: [never-runs]
     runs-on: ubuntu-latest
-    if: success()
+    if: ${{ !(cancelled() || failure()) }}
     steps:
       - run: |
           echo "Hello, successful"
-  
+
   runs-BECAUSE-needs-were-skipped:
     needs: [never-runs]
     runs-on: ubuntu-latest
-    # note we don't need '!cancelled()' or 'always()'
-    if: needs.never-runs.result == 'skipped'
+    if: |
+      !(cancelled() || failure())
+      && needs.never-runs.result == 'skipped'
     steps:
       - run: |
           echo "Opposite day!"
